FROM ubuntu:latest
USER root
# RUN apt-get update
# RUN apt-get dist-update -qqy
# RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
# RUN apt-get install -yqq wget apt-utils nodejs python3-pip libgpiod2

# RUN pip3 install --upgrade setuptools
# RUN pip3 install adafruit-circuitpython-dht adafruit-blinka RPI.GPIO

# # Yarn install
# ENV YARN_VERSION 1.16.0
# RUN \
#   apt-get update && \
#   wget --progress=dot:mega -O /tmp/yarn.deb https://github.com/yarnpkg/yarn/releases/download/v${YARN_VERSION}/yarn_${YARN_VERSION}_all.deb && \
#   apt-get install -qqy /tmp/yarn.deb && \
#   apt-get autoremove --purge -y && \
#   rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/* && \
#   yarn --version

# WORKDIR /frankyHome/api
# COPY package.json /frankyHome/api
# COPY yarn.lock /frankyHome/api
# COPY src /frankyHome/api/src
# RUN yarn

# CMD ["yarn", "start"]


